package com.example.SpringProductServiceProject.repository;

import com.example.SpringProductServiceProject.model.Product;
import org.springframework.data.jpa.repository.JpaRepository;

public interface ProductRepository extends JpaRepository<Product,Long> {

    Product save(Product p);
    //the attributes that are automatically returned will have the parameters
    //that will be generated by the DB
}
